SOURCE_DIRECTORY = src
OUTPUT_DIRECTORY = bin

SOURCE_FILE_CLIENT = $(SOURCE_DIRECTORY)/client.cpp
SOURCE_FILE_SERVER = $(SOURCE_DIRECTORY)/server.cpp

OUTPUT_FILE_CLIENT = $(OUTPUT_DIRECTORY)/client
OUTPUT_FILE_SERVER = $(OUTPUT_DIRECTORY)/server

CC = g++
CC_ADDITIONAL_FLAGS = -Wall

CODE_EDITOR = code

compile: $(OUTPUT_FILE_CLIENT) $(OUTPUT_FILE_SERVER)

$(OUTPUT_FILE_CLIENT): $(SOURCE_FILE_CLIENT)
	mkdir -p $(OUTPUT_DIRECTORY)
	$(CC) $(SOURCE_FILE_CLIENT) -o $(OUTPUT_FILE_CLIENT) $(CC_ADDITIONAL_FLAGS)

$(OUTPUT_FILE_SERVER): $(SOURCE_FILE_SERVER)
	mkdir -p $(OUTPUT_DIRECTORY)
	$(CC) $(SOURCE_FILE_SERVER) -o $(OUTPUT_FILE_SERVER) $(CC_ADDITIONAL_FLAGS)

run-client: $(OUTPUT_FILE_CLIENT)
	./$(OUTPUT_FILE_CLIENT)

run-server: $(OUTPUT_FILE_SERVER)
	./$(OUTPUT_FILE_SERVER)

develop:
	$(CODE_EDITOR) $(SOURCE_FILE_CLIENT) $(SOURCE_FILE_SERVER) Makefile

clean:
	rm -rf $(OUTPUT_DIRECTORY)